-- SELECT-only verification for FULLTEST_128_V2_20260828.
SELECT 'users' AS check_name,COUNT(*) AS value FROM users WHERE username LIKE 'fulltest128v2_%' AND email LIKE '%@fulltest128v2.local'
UNION ALL SELECT 'players',COUNT(*) FROM players p JOIN users u ON u.user_id=p.user_id WHERE u.username LIKE 'fulltest128v2_%' AND u.email LIKE '%@fulltest128v2.local'
UNION ALL SELECT 'teams',COUNT(*) FROM teams WHERE name LIKE '[FULLTEST128V2] %' AND game_id IS NULL AND status='active' AND is_solo_wrapper=0
UNION ALL SELECT 'team_members',COUNT(*) FROM team_members tm JOIN teams t ON t.team_id=tm.team_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'team_member_roles',COUNT(*) FROM team_member_roles r JOIN team_members tm ON tm.team_member_id=r.team_member_id JOIN teams t ON t.team_id=tm.team_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'tournaments',COUNT(*) FROM tournaments WHERE name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'categories',COUNT(*) FROM tournament_categories tc JOIN tournaments t ON t.tournament_id=tc.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'registrations',COUNT(*) FROM tournament_registrations tr JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'registration_members',COUNT(*) FROM tournament_registration_members rm JOIN tournament_registrations tr ON tr.tournament_registration_id=rm.tournament_registration_id JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'checkins',COUNT(*) FROM player_tournament_checkins c JOIN tournament_registrations tr ON tr.tournament_registration_id=c.tournament_registration_id JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %'
UNION ALL SELECT 'registration_history',COUNT(*) FROM registration_status_history h JOIN tournament_registrations tr ON tr.tournament_registration_id=h.tournament_registration_id JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %';
SELECT t.team_id,COUNT(*) AS members,SUM(LOWER(tm.in_game_role)='player') AS starters,SUM(LOWER(tm.in_game_role)='substitute') AS substitutes,SUM(LOWER(tm.in_game_role)='solo_player') AS solo_players,SUM(LOWER(tm.in_game_role)='coach') AS coaches,SUM(LOWER(tm.in_game_role)='manager') AS managers
FROM teams t JOIN team_members tm ON tm.team_id=t.team_id WHERE t.name LIKE '[FULLTEST128V2] %' GROUP BY t.team_id HAVING members<>9 OR starters<>5 OR substitutes<>1 OR solo_players<>1 OR coaches<>1 OR managers<>1;
SELECT COUNT(*) AS u18_wrong_gender_or_age FROM tournament_registration_members rm JOIN tournament_registrations tr ON tr.tournament_registration_id=rm.tournament_registration_id JOIN tournament_categories tc ON tc.tournament_category_id=tr.tournament_category_id JOIN tournaments t ON t.tournament_id=tr.tournament_id JOIN players p ON p.player_id=rm.player_id WHERE t.name='[FULLTEST128V2] RoV U18 Closed' AND ((tc.category_code='male' AND p.gender<>'male') OR (tc.category_code='female' AND p.gender<>'female') OR TIMESTAMPDIFF(YEAR,p.birth_date,t.start_date) NOT BETWEEN 13 AND 17);
SELECT COUNT(*) AS u18_roster_has_solo_player FROM tournament_registration_members rm JOIN tournament_registrations tr ON tr.tournament_registration_id=rm.tournament_registration_id JOIN tournaments t ON t.tournament_id=tr.tournament_id JOIN team_members tm ON tm.player_id=rm.player_id AND tm.in_game_role='solo_player' WHERE t.name='[FULLTEST128V2] RoV U18 Closed';
SELECT COUNT(*) AS roblox_wrong_age FROM tournament_registration_members rm JOIN tournament_registrations tr ON tr.tournament_registration_id=rm.tournament_registration_id JOIN tournaments t ON t.tournament_id=tr.tournament_id JOIN players p ON p.player_id=rm.player_id WHERE t.name='[FULLTEST128V2] Roblox Solo' AND TIMESTAMPDIFF(YEAR,p.birth_date,t.start_date) NOT BETWEEN 8 AND 12;
SELECT COUNT(*) AS solo_with_team FROM tournament_registrations tr JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] % Solo' AND tr.team_id IS NOT NULL;
SELECT COUNT(*) AS duplicate_registrations FROM tournament_registrations tr JOIN tournaments t ON t.tournament_id=tr.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %' GROUP BY tr.tournament_id,tr.team_id,tr.player_id,tr.tournament_category_id HAVING COUNT(*)>1;
SELECT COUNT(*) AS category_cross_tournament FROM tournament_registrations tr JOIN tournaments t ON t.tournament_id=tr.tournament_id LEFT JOIN tournament_categories tc ON tc.tournament_category_id=tr.tournament_category_id WHERE t.name LIKE '[FULLTEST128V2] %' AND (tc.tournament_id IS NULL OR tc.tournament_id<>tr.tournament_id);
SELECT COUNT(*) AS groups_created FROM tournament_groups tg JOIN tournaments t ON t.tournament_id=tg.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %';
SELECT COUNT(*) AS matches_created FROM matches m JOIN tournaments t ON t.tournament_id=m.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %';
SELECT COUNT(*) AS ranking_history_created FROM ranking_history rh JOIN tournaments t ON t.tournament_id=rh.tournament_id WHERE t.name LIKE '[FULLTEST128V2] %';
