<?php
// Full Test 128 V2 fixture. CLI only; dry-run by default. Never load schema helpers.
if (PHP_SAPI !== 'cli') { fwrite(STDERR, "CLI only\n"); exit(1); }
require __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/team_roles.php';
const V2_BATCH = 'FULLTEST_128_V2_20260828';
const V2_MANIFEST = __DIR__ . '/fulltest-FULLTEST_128_V2_20260828-manifest.json';
$options = getopt('', ['commit', 'backup-file:']);
$commit = array_key_exists('commit', $options);
$backupFile = $options['backup-file'] ?? '';
$manifest = ['batch' => V2_BATCH];
foreach (['users','players','teams','team_members','team_member_roles','tournaments','tournament_categories','tournament_registrations','tournament_registration_members','registration_status_history','player_tournament_checkins'] as $key) $manifest[$key] = [];
function v2Fail(string $message): void { throw new RuntimeException($message); }
function v2Table(PDO $pdo, string $table): bool { $s = $pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table'); $s->execute(['table'=>$table]); return (int)$s->fetchColumn() === 1; }
function v2Id(PDO $pdo, string $sql, array $params): int { $s=$pdo->prepare($sql);$s->execute($params);return (int)$pdo->lastInsertId(); }
function v2Game(PDO $pdo, string $pattern, string $mode, bool $u18 = false): int { $s=$pdo->prepare('SELECT g.game_id,g.name,COUNT(t.team_id) AS team_count FROM games g LEFT JOIN teams t ON t.game_id=g.game_id WHERE LOWER(g.name) LIKE :pattern AND g.play_mode=:mode AND g.is_active=1 GROUP BY g.game_id,g.name ORDER BY team_count DESC,g.game_id ASC');$s->execute(['pattern'=>'%'.strtolower($pattern).'%','mode'=>$mode]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);if(!$rows)v2Fail("Game not found: {$pattern}");if(!$u18&&count($rows)!==1)v2Fail("Ambiguous game: {$pattern}");if($u18&&count($rows)>1&&(int)$rows[0]['team_count']===(int)$rows[1]['team_count'])v2Fail("Ambiguous U18 game: {$pattern}");return(int)$rows[0]['game_id']; }
function v2Confirm(string $prompt,string $expected):void{fwrite(STDOUT,$prompt);if(trim((string)fgets(STDIN))!==$expected)v2Fail('Confirmation mismatch; stopped.');}
try {
    if ($pdo->query('SELECT DATABASE()')->fetchColumn() !== 'esport_korattest') v2Fail('Wrong database; stopped.');
    foreach (['users','players','games','teams','team_members','team_member_roles','tournaments','tournament_categories','tournament_registrations','tournament_registration_members','registration_status_history','player_tournament_checkins'] as $table) if (!v2Table($pdo,$table)) v2Fail("Missing table: {$table}");
    if (is_file(V2_MANIFEST)) v2Fail('V2 Manifest already exists; stopped.');
    $batch=$pdo->query("SELECT COUNT(*) FROM users WHERE username LIKE 'fulltest128v2_%' OR email LIKE '%@fulltest128v2.local'")->fetchColumn();if((int)$batch>0)v2Fail('Existing V2 users found; stopped.');
    $batch=$pdo->query("SELECT COUNT(*) FROM teams WHERE name LIKE '[FULLTEST128V2] %'")->fetchColumn();if((int)$batch>0)v2Fail('Existing V2 teams found; stopped.');
    $gameIds=['rov_open'=>v2Game($pdo,'Arena of Valor (RoV) - รุ่น Open','team'),'free_fire'=>v2Game($pdo,'Free Fire - รุ่น Open','team'),'rov_u18'=>v2Game($pdo,'Arena of Valor (RoV) - รุ่นอายุต่ำกว่า 18 ปี','team',true),'tekken'=>v2Game($pdo,'Tekken 8','solo'),'street_fighter'=>v2Game($pdo,'Street Fighter 6','solo'),'efootball'=>v2Game($pdo,'Efootball Mobile','solo'),'roblox'=>v2Game($pdo,'Roblox','solo')];
    foreach($gameIds as $key=>$id)echo "game_{$key}: {$id}\n";
    $plan=['users'=>1152,'players'=>1152,'teams'=>128,'team_members'=>1152,'team_member_roles'=>1152,'team_tournaments'=>6,'solo_tournaments'=>4,'team_registrations'=>640,'solo_registrations'=>512,'total_registrations'=>1152,'team_roster_members'=>5120,'solo_roster_members'=>512,'groups'=>0,'matches'=>0,'ranking_history'=>0];foreach($plan as $key=>$count)echo sprintf("%-28s %d\n",$key,$count);
    if(!$commit){echo "FULL TEST 128 V2 DRY RUN ONLY — NO DATA WAS WRITTEN\n";exit(0);}
    if($backupFile===''||!is_file($backupFile)||filesize($backupFile)<=0||filemtime($backupFile)<time()-7*86400)v2Fail('Recent non-empty --backup-file is required.');
    v2Confirm('Type database name to confirm: ','esport_korattest');v2Confirm('Type batch to confirm: ',V2_BATCH);
    $pdo->beginTransaction();
    $userHash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$answerHash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);
    $insertUser=$pdo->prepare("INSERT INTO users (username,email,password_hash,role,security_question,security_answer_hash,status) VALUES (:username,:email,:hash,'athlete','test',:answer,'active')");
    $insertPlayer=$pdo->prepare("INSERT INTO players (user_id,display_name,gender,birth_date,province,eligibility_status) VALUES (:user_id,:display_name,:gender,:birth_date,'นครราชสีมา','verified')");
    $playerIds=[];
    for($teamNo=1;$teamNo<=128;$teamNo++){ $gender=$teamNo<=64?'male':'female';for($memberNo=1;$memberNo<=9;$memberNo++){ $number=($teamNo-1)*9+$memberNo;$username=sprintf('fulltest128v2_%04d',$number);$insertUser->execute(['username'=>$username,'email'=>$username.'@fulltest128v2.local','hash'=>$userHash,'answer'=>$answerHash]);$userId=(int)$pdo->lastInsertId();$birthDate=$memberNo===7?'2014-06-15':'2010-06-15';$insertPlayer->execute(['user_id'=>$userId,'display_name'=>sprintf('[FULLTEST128V2] %s Player %04d',$gender,$number),'gender'=>$gender,'birth_date'=>$birthDate]);$playerId=(int)$pdo->lastInsertId();$playerIds[$teamNo][]=$playerId;$manifest['users'][]=$userId;$manifest['players'][]=$playerId;} }
    $teamIds=[];foreach($playerIds as $teamNo=>$players){$teamIds[$teamNo]=v2Id($pdo,"INSERT INTO teams (game_id,name,tag,captain_player_id,is_solo_wrapper,team_category,status) VALUES (NULL,:name,:tag,:captain,0,'open','active')",['name'=>sprintf('[FULLTEST128V2] Club %03d',$teamNo),'tag'=>sprintf('V2%03d',$teamNo),'captain'=>$players[0]]);$manifest['teams'][]=$teamIds[$teamNo];foreach($players as $memberIndex=>$playerId){$role=$memberIndex<5?'player':($memberIndex===5?'substitute':($memberIndex===6?'solo_player':($memberIndex===7?'coach':'manager')));$memberId=v2Id($pdo,'INSERT INTO team_members (team_id,player_id,in_game_role,member_roles,is_active,joined_at) VALUES (:team,:player,:role,:roles,1,NOW())',['team'=>$teamIds[$teamNo],'player'=>$playerId,'role'=>$role,'roles'=>$role==='solo_player'?'player':$role]);$roleId=v2Id($pdo,'INSERT INTO team_member_roles (team_member_id,role_code) VALUES (:member,:role)',['member'=>$memberId,'role'=>$role==='solo_player'?'player':$role]);$manifest['team_members'][]=$memberId;$manifest['team_member_roles'][]=$roleId;} }
    $createdBy=$manifest['users'][0];$specs=[['rov_completed','RoV Open Completed',$gameIds['rov_open'],'completed'],['free_open','Free Fire Open',$gameIds['free_fire'],'registration_open'],['u18_closed','RoV U18 Closed',$gameIds['rov_u18'],'registration_closed'],['rov_ongoing','RoV Open Ongoing',$gameIds['rov_open'],'ongoing'],['free_cancelled','Free Fire Cancelled',$gameIds['free_fire'],'cancelled'],['u18_draft','RoV U18 Draft',$gameIds['rov_u18'],'draft'],['tekken','Tekken Solo',$gameIds['tekken'],'registration_open'],['street_fighter','Street Fighter Solo',$gameIds['street_fighter'],'registration_open'],['efootball','Efootball Solo',$gameIds['efootball'],'registration_open'],['roblox','Roblox Solo',$gameIds['roblox'],'registration_open']];$tournaments=[];$insertTournament=$pdo->prepare("INSERT INTO tournaments (name,game_id,format,max_teams,registration_start,registration_end,start_date,end_date,status,created_by) VALUES (:name,:game,'single_elimination',128,:reg_start,:reg_end,:start,:end,:status,:created_by)");foreach($specs as [$key,$label,$game,$status]){$tournaments[$key]=v2Id($pdo,$insertTournament->queryString,['name'=>'[FULLTEST128V2] '.$label,'game'=>$game,'reg_start'=>date('Y-m-d H:i:s',time()-86400),'reg_end'=>date('Y-m-d H:i:s',time()+86400),'start'=>date('Y-m-d H:i:s',time()+172800),'end'=>date('Y-m-d H:i:s',time()+259200),'status'=>$status,'created_by'=>$createdBy]);$manifest['tournaments'][]=$tournaments[$key];}
    $categories=[];$categorySql="INSERT INTO tournament_categories (tournament_id,name,code,eligibility_type,minimum_age,maximum_age,category_code,label,max_participants,format,starters_count,substitutes_count,checkin_required_roles,is_active) VALUES (:tournament,:label,:code,:eligibility,:min_age,:max_age,:code,:label,128,'single_elimination',:starters,:substitutes,'player',1)";foreach(['rov_completed'=>[['open','Open','open',null,null]],'free_open'=>[['open','Open','open',null,null]],'u18_closed'=>[['male','Male','male',13,17],['female','Female','female',13,17]],'rov_ongoing'=>[['open','Open','open',null,null]],'free_cancelled'=>[['open','Open','open',null,null]],'u18_draft'=>[['male','Male','male',13,17],['female','Female','female',13,17]],'tekken'=>[['open','Open','open',null,null]],'street_fighter'=>[['open','Open','open',null,null]],'efootball'=>[['open','Open','open',null,null]],'roblox'=>[['open','Open','age_limited',8,12]]] as $key=>$rows)foreach($rows as [$code,$label,$eligibility,$minAge,$maxAge]){$categories[$key][$code]=v2Id($pdo,$categorySql,['tournament'=>$tournaments[$key],'label'=>$label,'code'=>$code,'eligibility'=>$eligibility,'min_age'=>$minAge,'max_age'=>$maxAge,'starters'=>in_array($key,['tekken','street_fighter','efootball','roblox'],true)?1:5,'substitutes'=>in_array($key,['tekken','street_fighter','efootball','roblox'],true)?0:1]);$manifest['tournament_categories'][]=$categories[$key][$code];}
    $insertReg=$pdo->prepare("INSERT INTO tournament_registrations (tournament_id,tournament_category_id,team_id,player_id,category,status,participation_status,checkin_status) VALUES (:tournament,:category,:team,:player,:code,:status,:participation,:checkin)");$insertMember=$pdo->prepare('INSERT INTO tournament_registration_members (tournament_registration_id,player_id,member_roles,is_starter,is_required_for_checkin,checkin_status) VALUES (:registration,:player,:role,:starter,:required,:checkin)');$insertCheckin=$pdo->prepare('INSERT INTO player_tournament_checkins (tournament_registration_id,player_id,checkin_status) VALUES (:registration,:player,:checkin)');$history=$pdo->prepare("INSERT INTO registration_status_history (tournament_registration_id,new_status,changed_by,change_note) VALUES (:registration,:status,:changed_by,:note)");
    $addTeam=function(string $key,int $teamNo,string $code)use(&$manifest,&$tournaments,&$categories,&$teamIds,&$playerIds,$insertReg,$insertMember,$insertCheckin,$history){$registration=v2Id($GLOBALS['pdo'],'INSERT INTO tournament_registrations (tournament_id,tournament_category_id,team_id,player_id,category,status,participation_status,checkin_status) VALUES (:tournament,:category,:team,NULL,:code,\'approved\',\'registered\',\'not_checked_in\')',['tournament'=>$tournaments[$key],'category'=>$categories[$key][$code],'team'=>$teamIds[$teamNo],'code'=>$code]);$manifest['tournament_registrations'][]=$registration;foreach([0,1,2,3,4,5,7,8] as $index){$role=$index<5?'player':($index===5?'substitute':($index===7?'coach':'manager'));$member=v2Id($GLOBALS['pdo'],'INSERT INTO tournament_registration_members (tournament_registration_id,player_id,member_roles,is_starter,is_required_for_checkin,checkin_status) VALUES (:registration,:player,:role,:starter,:required,\'not_checked_in\')',['registration'=>$registration,'player'=>$playerIds[$teamNo][$index],'role'=>$role,'starter'=>$index<5?1:0,'required'=>isRequiredCheckinRole([$role],'player')?1:0]);$checkin=v2Id($GLOBALS['pdo'],'INSERT INTO player_tournament_checkins (tournament_registration_id,player_id) VALUES (:registration,:player)',['registration'=>$registration,'player'=>$playerIds[$teamNo][$index]]);$manifest['tournament_registration_members'][]=$member;$manifest['player_tournament_checkins'][]=$checkin;}$history->execute(['registration'=>$registration,'status'=>'approved','changed_by'=>$manifest['users'][0],'note'=>V2_BATCH]);$manifest['registration_status_history'][]=(int)$GLOBALS['pdo']->lastInsertId();};
    $windowUpdate=$pdo->prepare('UPDATE tournaments SET checkin_open_at=:open_at, checkin_close_at=:close_at WHERE tournament_id=:tournament_id');foreach($tournaments as $tournamentId)$windowUpdate->execute(['open_at'=>date('Y-m-d H:i:s',time()+86400),'close_at'=>date('Y-m-d H:i:s',time()+172800),'tournament_id'=>$tournamentId]);
    foreach(['rov_completed','free_open','rov_ongoing','free_cancelled'] as $key)for($teamNo=1;$teamNo<=128;$teamNo++)$addTeam($key,$teamNo,'open');for($teamNo=1;$teamNo<=128;$teamNo++)$addTeam('u18_closed',$teamNo,$teamNo<=64?'male':'female');
    foreach(['tekken','street_fighter','efootball','roblox'] as $key)for($teamNo=1;$teamNo<=128;$teamNo++){$playerId=$playerIds[$teamNo][6];$registration=v2Id($pdo,'INSERT INTO tournament_registrations (tournament_id,tournament_category_id,team_id,player_id,category,status,participation_status,checkin_status) VALUES (:tournament,:category,NULL,:player,\'open\',\'approved\',\'registered\',\'not_checked_in\')',['tournament'=>$tournaments[$key],'category'=>$categories[$key]['open'],'player'=>$playerId]);$manifest['tournament_registrations'][]=$registration;$member=v2Id($pdo,"INSERT INTO tournament_registration_members (tournament_registration_id,player_id,member_roles,is_starter,is_required_for_checkin,checkin_status) VALUES (:registration,:player,'player',1,:required,'not_checked_in')",['registration'=>$registration,'player'=>$playerId,'required'=>isRequiredCheckinRole(['player'],'player')?1:0]);$checkin=v2Id($pdo,'INSERT INTO player_tournament_checkins (tournament_registration_id,player_id) VALUES (:registration,:player)',['registration'=>$registration,'player'=>$playerId]);$manifest['tournament_registration_members'][]=$member;$manifest['player_tournament_checkins'][]=$checkin;$history->execute(['registration'=>$registration,'status'=>'approved','changed_by'=>$manifest['users'][0],'note'=>V2_BATCH]);$manifest['registration_status_history'][]=(int)$pdo->lastInsertId();}
    $temporary=V2_MANIFEST.'.tmp';if(file_put_contents($temporary,json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))===false)v2Fail('Manifest write failed before commit.');$pdo->commit();if(!rename($temporary,V2_MANIFEST)){fwrite(STDERR,"Database committed but Manifest rename failed. Temporary Manifest retained at: {$temporary}\n");exit(1);}echo "Full Test V2 committed.\n";
} catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if(isset($temporary)&&is_file($temporary)&&!$commit)@unlink($temporary);fwrite(STDERR,'V2 stopped: '.$e->getMessage()."\n");exit(1);}
